### ISSUE TITLE
Check more tags for potential name match

### ISSUE THREAD

**Issue by starsep** [Zaczero/osm-warszawa-restauracje#1]
Example duplicate:
https://osm.org/node/333136439
https://osm.org/node/11068725455

Let's check other tags such as: `alt_name`, `official_name`, `short_name`, `loc_name`. Maybe `old_name` as well

Relevant code:
https://github.com/Zaczero/osm-warszawa-restauracje/blob/c28db2e67625bbc513a73b2e0515b655c0aa1d18/osm_search.py#L95

**Comment by Zaczero** [comment]
Maybe any key that has 'name' in it :smiley:.
